name: Comment on the pull request

on:
  workflow_run:
    workflows: ["Tests"]
    types:
      - completed

permissions:
  pull-requests: write

jobs:
  comment-on-pr:
    uses: canonical/operator-workflows/.github/workflows/comment.yaml@main
    permissions:
      pull-requests: write
    secrets: inherit
