name: Integration tests (microk8s 1.20)

on:
  pull_request:

jobs:
  integration-tests:
    uses: canonical/operator-workflows/.github/workflows/integration_test.yaml@main
    secrets: inherit
    with:
      channel: "1.20-strict/stable"
      modules: '["test_ingress_relation"]'
      juju-channel: 3.1/stable
