name: Publish to edge

on:
  push:
    branches:
    - main
    - track/*

permissions:
  actions: read
  contents: write

jobs:
  publish:
    uses: canonical/charm-ci/.github/workflows/publish-artifacts.yml@main
    permissions:
      actions: read
      contents: write
    with:
      channel: latest/edge
      integration-workflow-name: integration_test.yaml
    secrets:
      CHARMHUB_TOKEN: ${{ secrets.CHARMHUB_TOKEN }}
