name: Publish to edge

on:
  push:
    branches:
    - main
    - track/*

jobs:
  build:
    uses: canonical/charm-ci/.github/workflows/build-artifacts.yml@main
    permissions:
      contents: read
      packages: write
      actions: read

  publish:
    needs: build
    uses: canonical/charm-ci/.github/workflows/publish-artifacts.yml@main
    with:
      channel: latest/edge
    permissions:
      contents: read
      actions: read
    secrets: inherit
