name: Publish to edge

on:
  push:
    branches:
    - main
    - track/*

jobs:
  publish:
    uses: canonical/charm-ci/.github/workflows/publish-artifacts.yml@main
    with:
      channel: latest/edge
      integration-workflow-name: integration_test.yaml
    permissions:
      contents: read
      actions: read
    secrets: inherit
